name: expressjs app push to dockerhub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker Login
        run: echo "${{ secrets.PASSCODE }}" 

      - name: login to docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSCODE }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
            push: true
            tags: sreeram91/expressjs-app:latest