name: expressjs app push to dockerhub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.PASSCODE }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

      - name: build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: sreeram91/expressjs-app:latest